// ReSharper disable CheckNamespace
// ReSharper disable ClassNeverInstantiated.Global

// <auto-generated />

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace Immutype
{
    using System;
    using System.CodeDom.Compiler;

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Constructor, Inherited = false)]
    public class TargetAttribute: Attribute { }
}